### GET ALL PRODUCTS
GET http://localhost:4000/api/products HTTP/1.1

### GET SINGLE PRODUCT
GET http://localhost:4000/api/products/64d77f3778be9d979ecd9374 HTTP/1.1

### ADD ITEM
POST http://localhost:4000/api/products/ HTTP/1.1
Content-Type: application/json

{
    "title": "Google Pixel",
    "price": "Rs. 35k",
    "image": "https://www.mysmartprice.com/gear/google-pixel-3a-review/",
    "details": "32GB, 128GB"
}

### UPDATE ITEM
PUT http://localhost:4000/api/products/64d77f3778be9d979ecd9374 HTTP/1.1
Content-Type: application/json

{
    "title": "Motorola Edge"
}

### DELETE ITEM
DELETE http://localhost:4000/api/products/64d77f3778be9d979ecd9374 HTTP/1.1
